'use client';

import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Toaster} from "@/components/ui/toaster";
import Link from "next/link";
import {ThemeProvider} from "@/components/theme-provider";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Moved to next.config.js
// export const metadata: Metadata = {
//   title: 'SchoolVerse App',
//   description: 'Generated by Firebase Studio',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="bg-secondary p-4">
            <nav className="container mx-auto flex items-center justify-between">
              <div className="flex space-x-4">
                <Link href="/" className="hover:text-primary">Home</Link>
                <Link href="/student" className="hover:text-primary">Students</Link>
                <Link href="/teacher" className="hover:text-primary">Teachers</Link>
                <Link href="/about" className="hover:text-primary">About Us</Link>
                <Link href="/dashboard" className="hover:text-primary">Dashboard</Link>
              </div>
              <ThemeToggle />
            </nav>
          </header>
          <main className="container mx-auto">
            {children}
          </main>
          <Toaster/>
        </ThemeProvider>
      </body>
    </html>
  );
}

import { useTheme } from 'next-themes'
import { Moon, Sun } from 'lucide-react'
import { Button } from "@/components/ui/button"

function ThemeToggle() {
  const { setTheme } = useTheme()

  return (
    <div className="flex gap-2">
      <Button variant="outline" size="icon" onClick={() => setTheme('light')}>
        <Sun className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
        <span className="sr-only">Light</span>
      </Button>
      <Button variant="outline" size="icon" onClick={() => setTheme('dark')}>
        <Moon className="h-[1.2rem] w-[1.2rem] rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
        <span className="sr-only">Dark</span>
      </Button>
    </div>
  )
}
